export { default as Header} from "./Header" 
export { default as Nav} from "./Nav" 
export { default as Main} from "./Main" 
export { default as Ganime} from "./Ganime" 
export { default as AnimeM} from "./AnimeM" 